#ifndef __DEFENITIONS_H__
#define __DEFENITIONS_H__
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.0025
#define PIPE_MOVEMENT_SPEED 0.01
#define BIRD_FALLING_SPEED 0.0025
#define SCALE_RATIO 32
#endif // __DEFENITIONS_H__
